// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBHeH22wMaW3QGx_UzVzm71yAn9yOfpgrY',
    appId: '1:868714069112:web:3de971dec022efba55818d',
    messagingSenderId: '868714069112',
    projectId: 'money-5e752',
    authDomain: 'money-5e752.firebaseapp.com',
    storageBucket: 'money-5e752.appspot.com',
    measurementId: 'G-ZB0FNF91Z2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCpexT6HGwFhYLRMNpu83bA61-z87CVIbA',
    appId: '1:868714069112:android:8346e1deb317b30c55818d',
    messagingSenderId: '868714069112',
    projectId: 'money-5e752',
    storageBucket: 'money-5e752.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDr3BmsFTLgRL0LjztEsSW7lGYzUWXMeRM',
    appId: '1:868714069112:ios:56f236c599eef89b55818d',
    messagingSenderId: '868714069112',
    projectId: 'money-5e752',
    storageBucket: 'money-5e752.appspot.com',
    androidClientId: '868714069112-i8acnng53doea19m0ikb5ntet1ivpp90.apps.googleusercontent.com',
    iosClientId: '868714069112-k8qehr1cnio9fmdbe93ab68kr5r8gd2f.apps.googleusercontent.com',
    iosBundleId: 'com.example.moneyManagementApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDr3BmsFTLgRL0LjztEsSW7lGYzUWXMeRM',
    appId: '1:868714069112:ios:56f236c599eef89b55818d',
    messagingSenderId: '868714069112',
    projectId: 'money-5e752',
    storageBucket: 'money-5e752.appspot.com',
    androidClientId: '868714069112-i8acnng53doea19m0ikb5ntet1ivpp90.apps.googleusercontent.com',
    iosClientId: '868714069112-k8qehr1cnio9fmdbe93ab68kr5r8gd2f.apps.googleusercontent.com',
    iosBundleId: 'com.example.moneyManagementApp',
  );
}
